name: Support Request
description: Ask for help using this project
labels: [Support]
body:
  - type: textarea
    id: question
    attributes:
      label: Details
      description: Explain the issue or question as clearly as possible.
    validations:
      required: true
