---

- name: Create a text file from a template on the desktop
  ansible.builtin.template:
    src: "README.txt.j2"
    dest: "/home/{{ username }}/Desktop/README.txt"
    mode: '0644'
  become: false

- name: Create clear.sh in the home directory
  ansible.builtin.template:
    src: "clear.sh.j2"
    dest: "/home/{{ username }}/clear.sh"
    mode: '0755'
  become: false

- name: Create projects directory
  file:
    path: "/home/{{ username }}/Projects"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  become: true
