---

- include_tasks: update.yml
#- include_tasks: ssh.yml
- include_tasks: sudo.yml
- include_tasks: install.yml
- include_tasks: files.yml
- include_tasks: cron.yml
- include_tasks: motd.yml
- include_tasks: btrfs.yml
- include_tasks: sysctl.yml
- include_tasks: grub.yml
- include_tasks: systemd.yml
- include_tasks: readme.yml
