---

- name: Install XFCE packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ xfce_packages }}"
  become: true

# - name: Clone Fluent-gtk-theme repository
#   ansible.builtin.git:
#     repo: "https://github.com/vinceliuice/Fluent-gtk-theme.git"
#     dest: "/opt/Fluent-gtk-theme"
#     version: "master"

# - name: Ensure install script is executable
#   ansible.builtin.file:
#     path: "/opt/Fluent-gtk-theme/install.sh"
#     mode: '0755'

# - name: Run the install script
#   ansible.builtin.command:
#     cmd: "./install.sh -c dark -s standard -l --tweaks float round noborder"
#     chdir: "/opt/Fluent-gtk-theme"
#   become: true

# - name: Clone Fluent-icon-theme repository
#   ansible.builtin.git:
#     repo: "https://github.com/vinceliuice/Fluent-icon-theme.git"
#     dest: "/opt/Fluent-icon-theme"
#     version: "master"

# - name: Ensure install script is executable
#   ansible.builtin.file:
#     path: "/opt/Fluent-icon-theme/install.sh"
#     mode: '0755'

# - name: Run the install script
#   ansible.builtin.command:
#     cmd: "./install.sh"
#     chdir: "/opt/Fluent-icon-theme"
