---

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PHP and sqlite3 packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  become: true

- name: Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php

- name: Install Composer
  ansible.builtin.command:
    cmd: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
