---

- name: Check if VS Code is installed
  ansible.builtin.command: which code
  register: vscode_check
  ignore_errors: true
  changed_when: false

- name: Install VS Code
  block:
  - name: Download Microsoft GPG key
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /tmp/microsoft.asc
      mode: '0644'

  - name: Convert Microsoft GPG key to dearmored format
    ansible.builtin.command:
      cmd: gpg --dearmor -o /tmp/microsoft.gpg /tmp/microsoft.asc
    args:
      creates: /tmp/microsoft.gpg

  - name: Install Microsoft GPG key into keyrings
    ansible.builtin.command:
      cmd: install -D -o root -g root -m 644 /tmp/microsoft.gpg /usr/share/keyrings/microsoft.gpg
    args:
      creates: /usr/share/keyrings/microsoft.gpg

  - name: Remove temporary GPG files
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - /tmp/microsoft.asc
      - /tmp/microsoft.gpg

  - name: Add VS Code repository
    ansible.builtin.template:
      src: vscode.sources.j2
      dest: /etc/apt/sources.list.d/vscode.sources
      owner: root
      group: root
      mode: '0644'

  - name: Update APT cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install VS Code
    ansible.builtin.apt:
      name: code
      state: present
  when: vscode_check.rc != 0
